[package]
name = "rust-to-cpp"
version = "0.1.0"
edition = "2024"

[lib]
name = "librust"
crate-type = ["rlib", "cdylib"]

[dependencies]
cxx = "1.0.186"

[build-dependencies]
cxx-build = { version = "1.0.186", features = ["parallel"] }
